// <auto-generated/>
#pragma warning disable 1591
namespace Components.Account.Pages
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
#nullable restore
#line 3 "C:\Users\elnin\AppData\Local\Temp\8B34808D00BE469FE74422A095F95B5E501D\2\ElectroHub\ElectroHub\Components\Account\Pages\ConfirmEmail.razor"
using System.Text;

#nullable disable
#nullable restore
#line 4 "C:\Users\elnin\AppData\Local\Temp\8B34808D00BE469FE74422A095F95B5E501D\2\ElectroHub\ElectroHub\Components\Account\Pages\ConfirmEmail.razor"
using Microsoft.AspNetCore.Identity;

#nullable disable
#nullable restore
#line 5 "C:\Users\elnin\AppData\Local\Temp\8B34808D00BE469FE74422A095F95B5E501D\2\ElectroHub\ElectroHub\Components\Account\Pages\ConfirmEmail.razor"
using Microsoft.AspNetCore.WebUtilities;

#nullable disable
#nullable restore
#line 6 "C:\Users\elnin\AppData\Local\Temp\8B34808D00BE469FE74422A095F95B5E501D\2\ElectroHub\ElectroHub\Components\Account\Pages\ConfirmEmail.razor"
using ElectroHub.Data;
    using ElectroHub.Components.Account;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Components.RouteAttribute("/Account/ConfirmEmail")]
    #nullable restore
    public partial class ConfirmEmail : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 219
        private void __RazorDirectiveTokenHelpers__() {
        ((global::System.Action)(() => {
// language=Route,Component
#nullable restore
#line 1 "C:\Users\elnin\AppData\Local\Temp\8B34808D00BE469FE74422A095F95B5E501D\2\ElectroHub\ElectroHub\Components\Account\Pages\ConfirmEmail.razor"
global::System.Object __typeHelper = "/Account/ConfirmEmail";

#line default
#line hidden
#nullable disable
        }
        ))();
        ((global::System.Action)(() => {
#nullable restore
#line 8 "C:\Users\elnin\AppData\Local\Temp\8B34808D00BE469FE74422A095F95B5E501D\2\ElectroHub\ElectroHub\Components\Account\Pages\ConfirmEmail.razor"
UserManager<ApplicationUser> __typeHelper = default!;

#line default
#line hidden
#nullable disable
        }
        ))();
        ((global::System.Action)(() => {
#nullable restore
#line 8 "C:\Users\elnin\AppData\Local\Temp\8B34808D00BE469FE74422A095F95B5E501D\2\ElectroHub\ElectroHub\Components\Account\Pages\ConfirmEmail.razor"
global::System.Object UserManager = null!;

#line default
#line hidden
#nullable disable
        }
        ))();
        ((global::System.Action)(() => {
#nullable restore
#line 9 "C:\Users\elnin\AppData\Local\Temp\8B34808D00BE469FE74422A095F95B5E501D\2\ElectroHub\ElectroHub\Components\Account\Pages\ConfirmEmail.razor"
IdentityRedirectManager __typeHelper = default!;

#line default
#line hidden
#nullable disable
        }
        ))();
        ((global::System.Action)(() => {
#nullable restore
#line 9 "C:\Users\elnin\AppData\Local\Temp\8B34808D00BE469FE74422A095F95B5E501D\2\ElectroHub\ElectroHub\Components\Account\Pages\ConfirmEmail.razor"
global::System.Object RedirectManager = null!;

#line default
#line hidden
#nullable disable
        }
        ))();
        }
        #pragma warning restore 219
        #pragma warning disable 0414
        private static object __o = null;
        #pragma warning restore 0414
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __o = 
#nullable restore
#line 14 "C:\Users\elnin\AppData\Local\Temp\8B34808D00BE469FE74422A095F95B5E501D\2\ElectroHub\ElectroHub\Components\Account\Pages\ConfirmEmail.razor"
                         statusMessage

#line default
#line hidden
#nullable disable
            ;
        }
        #pragma warning restore 1998
#nullable restore
#line 16 "C:\Users\elnin\AppData\Local\Temp\8B34808D00BE469FE74422A095F95B5E501D\2\ElectroHub\ElectroHub\Components\Account\Pages\ConfirmEmail.razor"
       
    private string? statusMessage;

    [CascadingParameter]
    private HttpContext HttpContext { get; set; } = default!;

    [SupplyParameterFromQuery]
    private string? UserId { get; set; }

    [SupplyParameterFromQuery]
    private string? Code { get; set; }

    protected override async Task OnInitializedAsync()
    {
        if (UserId is null || Code is null)
        {
            RedirectManager.RedirectTo("");
            return;
        }

        var user = await UserManager.FindByIdAsync(UserId);
        if (user is null)
        {
            HttpContext.Response.StatusCode = StatusCodes.Status404NotFound;
            statusMessage = $"Error loading user with ID {UserId}";
        }
        else
        {
            var code = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(Code));
            var result = await UserManager.ConfirmEmailAsync(user, code);
            statusMessage = result.Succeeded ? "Thank you for confirming your email." : "Error confirming your email.";
        }
    }

#line default
#line hidden
#nullable disable
        [global::Microsoft.AspNetCore.Components.InjectAttribute] private IdentityRedirectManager RedirectManager { get; set; }
        [global::Microsoft.AspNetCore.Components.InjectAttribute] private UserManager<ApplicationUser> UserManager { get; set; }
    }
}
#pragma warning restore 1591
